version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file: .env
    working_dir: /var/www
    depends_on:
      - db
    links:
      - db
  db:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: "secret1"
      MYSQL_DATABASE: "pm_test_schema"
      MYSQL_USER: "homestead"
      MYSQL_PASSWORD: "secret2"
    volumes:
      - ./data/:/var/lib/mysql
    ports:
      - "3306:3306"
